import { Metadata } from 'next';
import React from 'react'

interface Props {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: "Klien Kami - Danzstore Official Website",
  description: "Generated by create next app",
};

const Layout = ({children}:Props) => {
  return (
    <div className="">
      {children}
    </div>
  )
}

export default Layout